export const CONFIG = {
  GRID_SIZE: 32, // pixels per tile
  MAP_WIDTH: 40,
  MAP_HEIGHT: 40,
  TICK_INTERVAL_MS: 100, // 10 Hz fixed simulation tick
  API_BASE_URL: '/api',
  
  // Lighting
  BASE_LIGHT_RADIUS: 1,
  TORCH_LIGHT_RADIUS: 6,
  LIGHT_SPELL_RADIUS: 7,
  LIGHT_SPELL_DURATION_SEC: 30,
  AMBIENT_LIGHT_RADIUS: 3,

  // Abilities & Combat
  MAGICIAN_SPARK_DAMAGE_MIN: 12,
  MAGICIAN_SPARK_DAMAGE_MAX: 16,
  MAGICIAN_SPARK_RANGE: 5,
  MAGICIAN_SPARK_COOLDOWN_SEC: 1.0,

  MAGICIAN_LIGHT_MANA_COST: 15,
  MAGICIAN_LIGHT_COOLDOWN_SEC: 5.0,

  MAGICIAN_BEAM_MANA_COST: 30,
  MAGICIAN_BEAM_DAMAGE_MIN: 30,
  MAGICIAN_BEAM_DAMAGE_MAX: 40,
  MAGICIAN_BEAM_RANGE: 4,
  MAGICIAN_BEAM_COOLDOWN_SEC: 3.0,

  ARCHER_BOW_DAMAGE_MIN: 14,
  ARCHER_BOW_DAMAGE_MAX: 18,
  ARCHER_BOW_RANGE: 6,
  ARCHER_BOW_COOLDOWN_SEC: 1.0,

  ARCHER_POWER_SHOT_DAMAGE_MIN: 32,
  ARCHER_POWER_SHOT_DAMAGE_MAX: 42,
  ARCHER_POWER_SHOT_RANGE: 6,
  ARCHER_POWER_SHOT_COOLDOWN_SEC: 4.0,

  // Monsters
  SKELETON_MOVE_CADENCE_SEC: 0.8,
  SKELETON_ATTACK_CADENCE_SEC: 1.5,
  SKELETON_DAMAGE_MIN: 8,
  SKELETON_DAMAGE_MAX: 14,

  CULTIST_MOVE_CADENCE_SEC: 1.0,
  CULTIST_ATTACK_CADENCE_SEC: 2.0,
  CULTIST_DAMAGE_MIN: 10,
  CULTIST_DAMAGE_MAX: 16,
  CULTIST_STANDOFF_MIN: 3,
  CULTIST_STANDOFF_MAX: 4,

  // Potions
  HEALTH_POTION_HEAL: 30,
  MANA_POTION_RESTORE: 40,
};
