export const CONFIG = {
  GRID_SIZE: 32, // pixels per tile
  MAP_WIDTH: 40,
  MAP_HEIGHT: 40,
  TICK_INTERVAL_MS: 100, // 10 Hz fixed simulation tick
  API_BASE_URL: '/api',

  // Gesture Engine Timing Thresholds
  TAP_MAX_MS: 250, // Release < 250ms = Tap
  HOLD_MIN_MS: 250, // Hold >= 250ms = Charge
  HOLD_MAX_MS: 1500, // Maximum hold duration for 100% charge
  DOUBLE_TAP_MAX_MS: 300, // Second press within 300ms = Double-Tap

  // Container Limits
  ACTION_BAR_SLOTS: 10,
  BACKPACK_SLOTS: 6,
  PAPERDOLL_SLOT_NAMES: ['main_hand', 'off_hand', 'armor', 'relic'] as const,

  // Lighting
  BASE_LIGHT_RADIUS: 1,
  TORCH_LIGHT_RADIUS: 6,
  LIGHT_SPELL_RADIUS: 7,
  LIGHT_SPELL_DURATION_SEC: 30,
  AMBIENT_LIGHT_RADIUS: 3,

  // Vocation Base Stats
  MAGICIAN_BASE_HP: 60,
  MAGICIAN_BASE_MANA: 150,
  ARCHER_BASE_HP: 90,
  ARCHER_BASE_MANA: 80,
  FIGHTER_BASE_HP: 140,
  FIGHTER_BASE_MANA: 30,
  PALADIN_BASE_HP: 120,
  PALADIN_BASE_MANA: 90,

  // Abilities & Combat: Magician
  MAGICIAN_SPARK_DAMAGE_MIN: 12,
  MAGICIAN_SPARK_DAMAGE_MAX: 16,
  MAGICIAN_SPARK_RANGE: 5,
  MAGICIAN_SPARK_COOLDOWN_SEC: 1.0,

  MAGICIAN_LIGHT_MANA_COST: 15,
  MAGICIAN_LIGHT_COOLDOWN_SEC: 5.0,

  MAGICIAN_BEAM_MANA_COST: 30,
  MAGICIAN_BEAM_DAMAGE_MIN: 30,
  MAGICIAN_BEAM_DAMAGE_MAX: 40,
  MAGICIAN_BEAM_RANGE: 4,
  MAGICIAN_BEAM_COOLDOWN_SEC: 3.0,

  // Abilities & Combat: Archer
  ARCHER_BOW_DAMAGE_MIN: 14,
  ARCHER_BOW_DAMAGE_MAX: 18,
  ARCHER_BOW_RANGE: 6,
  ARCHER_BOW_COOLDOWN_SEC: 1.0,

  ARCHER_POWER_SHOT_DAMAGE_MIN: 32,
  ARCHER_POWER_SHOT_DAMAGE_MAX: 42,
  ARCHER_POWER_SHOT_RANGE: 6,
  ARCHER_POWER_SHOT_COOLDOWN_SEC: 4.0,

  // Abilities & Combat: Fighter
  FIGHTER_SLASH_DAMAGE_MIN: 16,
  FIGHTER_SLASH_DAMAGE_MAX: 22,
  FIGHTER_SLASH_COOLDOWN_SEC: 0.8,

  FIGHTER_CLEAVE_DAMAGE_MIN: 24,
  FIGHTER_CLEAVE_DAMAGE_MAX: 34,
  FIGHTER_CLEAVE_COOLDOWN_SEC: 2.5,
  FIGHTER_CLEAVE_MANA_COST: 10,

  FIGHTER_FORTIFY_MANA_COST: 15,
  FIGHTER_FORTIFY_DURATION_SEC: 10.0,
  FIGHTER_FORTIFY_COOLDOWN_SEC: 12.0,

  // Abilities & Combat: Paladin
  PALADIN_HOLY_STRIKE_DAMAGE_MIN: 18,
  PALADIN_HOLY_STRIKE_DAMAGE_MAX: 26,
  PALADIN_HOLY_STRIKE_COOLDOWN_SEC: 1.2,
  PALADIN_HOLY_STRIKE_MANA_COST: 10,

  PALADIN_HEAL_AMOUNT_MIN: 35,
  PALADIN_HEAL_AMOUNT_MAX: 50,
  PALADIN_HEAL_MANA_COST: 25,
  PALADIN_HEAL_COOLDOWN_SEC: 6.0,

  PALADIN_RADIANCE_MANA_COST: 30,
  PALADIN_RADIANCE_DAMAGE_MIN: 20,
  PALADIN_RADIANCE_DAMAGE_MAX: 30,
  PALADIN_RADIANCE_COOLDOWN_SEC: 8.0,

  // Monsters
  SKELETON_MOVE_CADENCE_SEC: 0.8,
  SKELETON_ATTACK_CADENCE_SEC: 1.5,
  SKELETON_DAMAGE_MIN: 8,
  SKELETON_DAMAGE_MAX: 14,

  CULTIST_MOVE_CADENCE_SEC: 1.0,
  CULTIST_ATTACK_CADENCE_SEC: 2.0,
  CULTIST_DAMAGE_MIN: 10,
  CULTIST_DAMAGE_MAX: 16,
  CULTIST_STANDOFF_MIN: 3,
  CULTIST_STANDOFF_MAX: 4,

  // Potions
  HEALTH_POTION_HEAL: 30,
  MANA_POTION_RESTORE: 40,
};
